### ISSUE TITLE
FileNotFoundError: libtorchaudio.pyd

### ISSUE THREAD

**Issue by ThinkMcFlyThink** [drcassar/glasspy#13]
**Setup:**
Windows 10
Python 3.11.6 (64bit) & Python 3.9.13 (64bit)

**Code:**
```
from glasspy.predict import GlassNet

model = GlassNet()
composition = "Li2O(SiO2)2"
predictions = model.predict(composition)
print(predictions)
```

**Expected output:**
Table as shown in https://glasspy.readthedocs.io/en/latest/intro/notebooks/glasspy_predict.html

**Actual output:**
FileNotFoundError: Could not find module 'C:\Program Files\Python311\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax. 

**Comments:**
I have tried this on fresh installs for both Python versions and get the same error. The file "libtorchaudio.pyd" is in the folder specified in the error. This is the same for both Python versions.

**Comment by ThinkMcFlyThink** [comment]
Update:

Strangely enough, using Python 3.11.6 and downgrading the torch CUDA version from 11.8 to 11.7 via: 
`pip install torch==2.0.1+cu117 torchvision==0.15.2+cu117 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu117` appears to fix the issue.

I now only get a warning "UserWarning: No audio backend is available". The output now shows the table as per the example.

I will try a few more things to make sure all is working as expected before closing this.

**Comment by drcassar** [comment]
Hi @ThinkMcFlyThink and thanks for oppening the issue!

The best strategy is to install pytorch yourself (following the official instructions) and then install GlassPy. I will add this information in the documentation and the README.
