### ISSUE TITLE
Integration to SciGlass Next

### ISSUE THREAD

**Issue by Lexachoc** [drcassar/glasspy#16]
Hello @drcassar,

I'm the creator of [SciGlass Next](https://sciglass.uni-jena.de/).

I would like to integrate some glass property prediction models into the SciGlass Next Python backend.
GlassNet seems to be the only open source (python) model so far in the internet.🤔
I am very appreciative of your work!

The current plan is to integrate ML models from our group developed by my colleague (papers submitted) and [GlassNet] (https://arxiv.org/abs/2303.15538).

Before I continue, I would like to ask 

1. If there will be any major updates to the package? (I saw there's a dev branch)

2. And also regarding performance, does the user benefit from having a GPU when making prediction or training?
(I will mainly focus on the prediction part for the integration and won't retrain the model).

I will first make a prediction for all data that falls within the range and store the predicted values in the database.
And the web interface is used to predict properties from glass compositions entered by the user (simple use case).
Or for the advanced use case, batch predictions all at once. (this will probably take longer time for our server)

I will get back to you when I have more information (UI designs or some benchmarks) and hope you can give me your feedback or insights and even ideas for the UI design!

**Comment by drcassar** [comment]
Hello @Lexachoc,

Congratulations on creating SciGlass Next!

I am glad that you want to integrate GlassNet into SciGlass Next. Go ahead and feel free to contact me for feedback. 

Answering your questions

1. There are no major updates planned for the foreseeable future. Version 0.5 will (hopefully) be released soon, it will change the single-task models (minor improvement) and update the scikit-learn version. It might be a good idea to check it out in the dev branch before release. But please keep in mind that GlassPy is still under development, albeit slowly, and there may be API changes in the future, as stated in the README.
2. Training is much faster using the GPU. Inference should also be faster, but depending on the amount of data, you may be able to get away with just using the CPU. For my personal use, I always do inference with GlassNet using the CPU, even with large amounts of data.

I will close this issue. Feel free to contact me by mail (see my recent publications) or via ResearchGate.
All the best
