### ISSUE TITLE
The amount of database

### ISSUE THREAD

**Issue by Wi1sonchen** [drcassar/glasspy#5]
I want to know why you drop some data from the original database?

**Comment by drcassar** [comment]
Hi @Wi1sonchen, thanks for oppening the issue. It is not trivial to understand what is inside the SciGlass database. The data provided is what I was somewhat confident at the time. In a future update I'll add more data.

**Comment by drcassar** [comment]
Hi @Wi1sonchen. GlassPy now has much more data from SciGlass. Check version 0.4 if you are interested. I am closing this issue.
